// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_LiQML)
QT_DECLARE_EXTERN_RESOURCE(qmake_LiQML)
QT_DECLARE_EXTERN_RESOURCE(LiQML_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_LiQML)

class LiQMLPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    LiQMLPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_LiQML)
QT_KEEP_RESOURCE(qmlcache_LiQML)
QT_KEEP_RESOURCE(qmake_LiQML)
QT_KEEP_RESOURCE(LiQML_raw_qml_0)
    }
};



#include "LiQMLplugin_LiQMLPlugin.moc"
