### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(StudyProjectContent)
add_subdirectory(Li)
add_subdirectory(StudyProject)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    StudyProjectContentplugin
    Liplugin
    StudyProjectplugin)