// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_LiQMLContent)
QT_DECLARE_EXTERN_RESOURCE(qmake_LiQMLContent)
QT_DECLARE_EXTERN_RESOURCE(LiQMLContent_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_LiQMLContent)

class LiQMLContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    LiQMLContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_LiQMLContent)
QT_KEEP_RESOURCE(qmlcache_LiQMLContent)
QT_KEEP_RESOURCE(qmake_LiQMLContent)
QT_KEEP_RESOURCE(LiQMLContent_raw_qml_0)
    }
};



#include "LiQMLContentplugin_LiQMLContentPlugin.moc"
